services:
  db:
    image: postgres:latest
    container_name: fitness_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Renegade187!
      POSTGRES_DB: gormproject
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - fitness-network

  api:
    build:
      context: .
    container_name: fitness_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Renegade187!
      DB_NAME: gormproject
      DB_PORT: 5432
    ports:
      - "8080:8080"
    networks:
      - fitness-network

networks:
  fitness-network:
    driver: bridge

volumes:
  db-data: