namespace: lmw-harness
GO_ENV: production

api:
  port: 8081
  type: NodePort
  nodePort: 30260
  host: api.lmw-fitness.com
  path: /api/
  pathType: ImplementationSpecific

image:
  repository: lmwcode/backend-go-fitness-locator
  pullPolicy: Always
  tag: v.<+pipeline.sequenceId>

replicaCount: 1

database:
  name: gormproject
  user: postgres
  port: 5432
  servicePort: 5433
  type: ClusterIP
  sslMode: disable

secrets:
  dbPassword: <+secrets.getValue("db_password_harness_secret")>
  accessKey: <+secrets.getValue("access_key_harness_secret")>
  refreshKey: <+secrets.getValue("refresh_key_harness_secret")>
  adminPassword: <+secrets.getValue("admin_password_harness_secret")>

storage:
  storageClass: nfs-csi

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
