namespace: lmw-fitness
GO_ENV: production

api:
  port: 8081
  type: NodePort  
  nodePort: 30260
  host: api.lmw-fitness.com
  path: /api/
  pathType: ImplementationSpecific

image:
  repository: lmwcode/go-backend-fitness-locator:e632506a358f4d6d3fcf0f15d46830d1343f931a
  pullPolicy: Always

replicaCount: 1

database:
  name: gormproject
  user: postgres
  port: 5432
  servicePort: 5433
  type: ClusterIP
  sslMode: disable

storage:
  storageClass: nfs-csi

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3