namespace: lmw-harness
GO_ENV: production

api:
  port: 8081
  type: NodePort
  nodePort: 30260
  host: api.lmw-fitness.com
  path: /api/
  pathType: ImplementationSpecific

image:
  repository: lmwcode/backend-go-fitness-locator
  pullPolicy: Always
  tag: v.<+pipeline.sequenceId>

replicaCount: 1

database:
  name: gormproject
  user: postgres
  port: 5432
  servicePort: 5433
  type: ClusterIP
  sslMode: disable

secrets:
  dbPassword: <+pipeline.variables.dbPassword>
  accessSecretKey: <+pipeline.variables.accessSecretKey>
  refreshSecretKey: <+pipeline.variables.refreshSecretKey>
  adminPassword: <+pipeline.variables.adminPassword>

cookies:
  env: development
  devDomain: http://localhost:5050
  devSecureCookie: false
  devHttpOnlyCookie: false
  prodDomain: http://172.16.6.178:5050
  prodSecureCookie: true
  prodHttpOnlyCookie: true

storage:
  storageClass: nfs-csi

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
