apiVersion: v1
kind: ConfigMap
metadata:
  name: lmw-fitness-backend-configmap
  namespace: {{ .Values.namespace }}
data:
  GO_ENV: "{{ .Values.env }}"
  PORT: "{{ .Values.api.port }}"
  DB_HOST: "lmw-fitness-postgres-service"
  DB_USER: "{{ .Values.database.user }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_SSLMODE: "{{ .Values.database.sslMode }}"
  STORAGE_CLASS: "{{ .Values.storage.storageClass }}"
  ENV: "{{ .Values.cookies.env }}"
  DEV_DOMAIN: "{{ .Values.cookies.devDomain }}"
  DEV_SECURE_COOKIE: "{{ .Values.cookies.devSecureCookie }}"
  DEV_HTTP_ONLY_COOKIE: "{{ .Values.cookies.devHttpOnlyCookie }}"
  PROD_DOMAIN: "{{ .Values.cookies.prodDomain }}"
  PROD_SECURE_COOKIE: "{{ .Values.cookies.prodSecureCookie }}"
  PROD_HTTP_ONLY_COOKIE: "{{ .Values.cookies.prodHttpOnlyCookie }}"