apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmw-fitness-postgres-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmw-fitness-postgres-deployment
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lmw-fitness-postgres
  template:
    metadata:
      labels:
        app: lmw-fitness-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: {{ .Values.database.port }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: lmw-fitness-backend-configmap
              key: DB_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: lmw-fitness-backend-configmap
              key: DB_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: lmw-fitness-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lmw-fitness-postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmw-fitness-postgres-service
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  selector:
    app: lmw-fitness-postgres
  ports:
  - port: {{ .Values.database.servicePort }}
    targetPort: {{ .Values.database.port }}
    protocol: TCP
  type: {{ .Values.database.type }}
