apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: lmw-harness
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.secrets.ACCESS_SECRET_KEY | b64enc | quote }}
  REFRESH_SECRET_KEY: {{ .Values.secrets.REFRESH_SCERET_KEY | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.ADMIN_PASSWORD | b64enc | quote }}