apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: lmw-harness
type: Opaque
data:
  DB_PASSWORD: <+secrets.getValue("DB_PASSWORD")>
  ACCESS_SECRET_KEY: <+secrets.getValue("ACCESS_SECRET_KEY")>
  REFRESH_SECRET_KEY: <+secrets.getValue("REFRESH_SECRET_KEY")>
  ADMIN_PASSWORD: <+secrets.getValue("ADMIN_PASSWORD")>