apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: lmw-harness
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  ACCESS_SECRET_KEY: {{ .Values.secrets.accessKey | quote }}
  REFRESH_SECRET_KEY: {{ .Values.secrets.refreshKey | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}