apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: lmw-harness
type: Opaque
data:
  DB_PASSWORD: <+secrets.getValueBase64("DB_PASSWORD")>
  ACCESS_SECRET_KEY: <+secrets.getValueBase64("ACCESS_SECRET_KEY")>
  REFRESH_SECRET_KEY: <+secrets.getValueBase64("REFRESH_SECRET_KEY")>
  ADMIN_PASSWORD: <+secrets.getValueBase64("ADMIN_PASSWORD")>