apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lmw-fitness-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: lmw-fitness-postgres-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmw-fitnes-backend-deployment
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  volumeName: lmw-fitness-postgres-pv
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lmw-fitness-postgres-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lmw-fitness-backend-deployment
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" 