apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-lmw-deployment
  namespace: lmwprac
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: go-backend-fitness-locator
    meta.helm.sh/release-namespace: lmwprac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: backend
        image: lmwcode/fitness_locator-api:V1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-lmw-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-lmw-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-lmw-secret
              key: POSTGRES_DB
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-lmw-secret
              key: ADMIN_PASSWORD

        - name: PORT
          valueFrom:
            secretKeyRef:
              name: port-lmw-secret
              key: PORT
        
        - name: ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-lmw-secret
              key: ACCESS_SECRET_KEY
        - name: REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-lmw-secret
              key: REFRESH_SECRET_KEY
        
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: ENV
        - name: DEV_DOMAIN
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: DEV_DOMAIN
        - name: DEV_SECURE_COOKIE
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: DEV_SECURE_COOKIE
        - name: DEV_HTTP_ONLY_COOKIE
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: DEV_HTTP_ONLY_COOKIE
        - name: PROD_DOMAIN
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: PROD_DOMAIN
        - name: PROD_SECURE_COOKIE
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: PROD_SECURE_COOKIE
        - name: PROD_HTTP_ONLY_COOKIE
          valueFrom:
            secretKeyRef:
              name: cookie-lmw-secret
              key: PROD_HTTP_ONLY_COOKIE
        
        readinessProbe:
          httpGet:
            path: /api/
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 120
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 120
          failureThreshold: 3
