apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lmwprac
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: react-frontend-fitness-locator
    meta.helm.sh/release-namespace: lmwprac
spec:
  selector:
    app: backend
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP